import type { LanguageName } from "@uiw/codemirror-extensions-langs";

export type LanguageValue = LanguageName | "plaintext";

interface Language {
  name: string;
  value: LanguageValue;
}

const languagesList: Language[] = [
  { name: "Plain Text", value: "plaintext" },
  { name: "Angular", value: "angular" },
  { name: "APL", value: "apl" },
  { name: "AsciiArmor", value: "asciiArmor" },
  { name: "Asterisk", value: "asterisk" },
  { name: "Brainfuck", value: "brainfuck" },
  { name: "C", value: "c" },
  { name: "Clojure", value: "clojure" },
  { name: "CMake", value: "cmake" },
  { name: "COBOL", value: "cobol" },
  { name: "CoffeeScript", value: "coffeescript" },
  { name: "Common Lisp", value: "commonLisp" },
  { name: "C++", value: "cpp" },
  { name: "Crystal", value: "crystal" },
  { name: "C#", value: "csharp" },
  { name: "CSS", value: "css" },
  { name: "Cypher", value: "cypher" },
  { name: "D", value: "d" },
  { name: "Dart", value: "dart" },
  { name: "Diff", value: "diff" },
  { name: "Dockerfile", value: "dockerfile" },
  { name: "DTD", value: "dtd" },
  { name: "Dylan", value: "dylan" },
  { name: "EBNF", value: "ebnf" },
  { name: "ECL", value: "ecl" },
  { name: "Eiffel", value: "eiffel" },
  { name: "Elm", value: "elm" },
  { name: "Erlang", value: "erlang" },
  { name: "Factor", value: "factor" },
  { name: "FCL", value: "fcl" },
  { name: "Forth", value: "forth" },
  { name: "Fortran", value: "fortran" },
  { name: "GAS", value: "gas" },
  { name: "Gherkin", value: "gherkin" },
  { name: "Go", value: "go" },
  { name: "Groovy", value: "groovy" },
  { name: "Haskell", value: "haskell" },
  { name: "Haxe", value: "haxe" },
  { name: "HTML", value: "html" },
  { name: "HTTP", value: "http" },
  { name: "IDL", value: "idl" },
  { name: "Java", value: "java" },
  { name: "JavaScript", value: "javascript" },
  { name: "Jinja2", value: "jinja2" },
  { name: "JSON", value: "json" },
  { name: "JSX", value: "jsx" },
  { name: "Julia", value: "julia" },
  { name: "Kotlin", value: "kotlin" },
  { name: "Less", value: "less" },
  { name: "Lezer", value: "lezer" },
  { name: "Liquid", value: "liquid" },
  { name: "LiveScript", value: "livescript" },
  { name: "Lua", value: "lua" },
  { name: "Markdown", value: "markdown" },
  { name: "Mathematica", value: "mathematica" },
  { name: "MBOX", value: "mbox" },
  { name: "Mermaid", value: "mermaid" },
  { name: "mIRC", value: "mirc" },
  { name: "Modelica", value: "modelica" },
  { name: "mscgen", value: "mscgen" },
  { name: "MUMPS", value: "mumps" },
  { name: "MySQL", value: "mysql" },
  { name: "nesC", value: "nesC" },
  { name: "Nginx", value: "nginx" },
  { name: "Nix", value: "nix" },
  { name: "NSIS", value: "nsis" },
  { name: "ntriples", value: "ntriples" },
  { name: "Objective-C", value: "objectiveC" },
  { name: "Objective-C++", value: "objectiveCpp" },
  { name: "Octave", value: "octave" },
  { name: "Oz", value: "oz" },
  { name: "Pascal", value: "pascal" },
  { name: "Perl", value: "perl" },
  { name: "PostgreSQL", value: "pgsql" },
  { name: "PHP", value: "php" },
  { name: "Pig", value: "pig" },
  { name: "PowerShell", value: "powershell" },
  { name: "Properties", value: "properties" },
  { name: "Protocol Buffers", value: "protobuf" },
  { name: "Puppet", value: "puppet" },
  { name: "Python", value: "python" },
  { name: "Q", value: "q" },
  { name: "R", value: "r" },
  { name: "Ruby", value: "ruby" },
  { name: "Rust", value: "rust" },
  { name: "SAS", value: "sas" },
  { name: "Sass", value: "sass" },
  { name: "Scala", value: "scala" },
  { name: "Scheme", value: "scheme" },
  { name: "Shader", value: "shader" },
  { name: "Shell", value: "shell" },
  { name: "Sieve", value: "sieve" },
  { name: "Smalltalk", value: "smalltalk" },
  { name: "Solidity", value: "solidity" },
  { name: "Solr", value: "solr" },
  { name: "SPARQL", value: "sparql" },
  { name: "Spreadsheet", value: "spreadsheet" },
  { name: "SQL", value: "sql" },
  { name: "Squirrel", value: "squirrel" },
  { name: "sTeX", value: "stex" },
  { name: "Stylus", value: "stylus" },
  { name: "Svelte", value: "svelte" },
  { name: "Swift", value: "swift" },
  { name: "Tcl", value: "tcl" },
  { name: "Textile", value: "textile" },
  { name: "TiddlyWiki", value: "tiddlyWiki" },
  { name: "Tiki", value: "tiki" },
  { name: "TOML", value: "toml" },
  { name: "Troff", value: "troff" },
  { name: "TSX", value: "tsx" },
  { name: "TTCN", value: "ttcn" },
  { name: "Turtle", value: "turtle" },
  { name: "TypeScript", value: "typescript" },
  { name: "Visual Basic", value: "vb" },
  { name: "VBScript", value: "vbscript" },
  { name: "Velocity", value: "velocity" },
  { name: "Verilog", value: "verilog" },
  { name: "VHDL", value: "vhdl" },
  { name: "Vue", value: "vue" },
  { name: "wast", value: "wast" },
  { name: "Web IDL", value: "webIDL" },
  { name: "XML", value: "xml" },
  { name: "xQuery", value: "xQuery" },
  { name: "Yacas", value: "yacas" },
  { name: "YAML", value: "yaml" },
  { name: "Z80", value: "z80" },
];

export default languagesList;
