interface Language {
  name: string;
  value: string;
}

const languagesList: Language[] = [
  { name: "6502 Assembly", value: "asm6502" },
  { name: "Assembly", value: "asm" },
  { name: "ABAP", value: "abap" },
  { name: "ActionScript", value: "actionscript" },
  { name: "Ada", value: "ada" },
  { name: "Agda", value: "agda" },
  { name: "Apex", value: "apex" },
  { name: "APL", value: "apl" },
  { name: "Arduino", value: "arduino" },
  { name: "Bash", value: "bash" },
  { name: "BASIC", value: "basic" },
  { name: "Batch", value: "batch" },
  { name: "BNF", value: "bnf" },
  { name: "C", value: "c" },
  { name: "C#", value: "csharp" },
  { name: "C++", value: "cpp" },
  { name: "Clojure", value: "clojure" },
  { name: "CMake", value: "cmake" },
  { name: "COBOL", value: "cobol" },
  { name: "CoffeeScript", value: "coffeescript" },
  { name: "Coq", value: "coq" },
  { name: "Crystal", value: "crystal" },
  { name: "CSS", value: "css" },
  { name: "D", value: "d" },
  { name: "Dart", value: "dart" },
  { name: "Dhall", value: "dhall" },
  { name: "Diff", value: "diff" },
  { name: "EBNF", value: "ebnf" },
  { name: "Elixir", value: "elixir" },
  { name: "Elm", value: "elm" },
  { name: "Erlang", value: "erlang" },
  { name: "F#", value: "fsharp" },
  { name: "Flow", value: "flow" },
  { name: "Fortran", value: "fortran" },
  { name: "Gherkin", value: "gherkin" },
  { name: "GLSL", value: "glsl" },
  { name: "Go", value: "go" },
  { name: "GraphQL", value: "graphql" },
  { name: "Groovy", value: "groovy" },
  { name: "Haskell", value: "haskell" },
  { name: "HTML", value: "html" },
  { name: "Idris", value: "idris" },
  { name: "Java", value: "java" },
  { name: "Javadoc", value: "javadoc" },
  { name: "JavaScript", value: "javascript" },
  { name: "JSON", value: "json" },
  { name: "Julia", value: "julia" },
  { name: "Kotlin", value: "kotlin" },
  { name: "LaTeX", value: "latex" },
  { name: "Less", value: "less" },
  { name: "Lisp", value: "lisp" },
  { name: "LiveScript", value: "livescript" },
  { name: "LLVM IR", value: "llvm" },
  { name: "Lua", value: "lua" },
  { name: "Makefile", value: "makefile" },
  { name: "Markdown", value: "markdown" },
  { name: "Markup", value: "markup" },
  { name: "MATLAB", value: "matlab" },
  { name: "Mermaid", value: "mermaid" },
  { name: "nginx", value: "nginx" },
  { name: "Nim", value: "nim" },
  { name: "Nix", value: "nix" },
  { name: "Objective-C", value: "objectivec" },
  { name: "OCaml", value: "ocaml" },
  { name: "Pascal", value: "pascal" },
  { name: "Perl", value: "perl" },
  { name: "PHP", value: "php" },
  { name: "Plain Text", value: "plaintext" },
  { name: "PowerShell", value: "powershell" },
  { name: "Prolog", value: "prolog" },
  { name: "Protocol Buffers", value: "protobuf" },
  { name: "PureScript", value: "purescript" },
  { name: "Python", value: "python" },
  { name: "R", value: "r" },
  { name: "Racket", value: "racket" },
  { name: "Reason", value: "reason" },
  { name: "Regular expression", value: "regex" },
  { name: "Ruby", value: "ruby" },
  { name: "Rust", value: "rust" },
  { name: "SAS", value: "sas" },
  { name: "Sass", value: "sass" },
  { name: "Scala", value: "scala" },
  { name: "Scheme", value: "scheme" },
  { name: "Scss", value: "scss" },
  { name: "Shell", value: "shell" },
  { name: "Solidity", value: "solidity" },
  { name: "SQL", value: "sql" },
  { name: "Swift", value: "swift" },
  { name: "Systemd", value: "systemd" },
  { name: "Tcl", value: "tcl" },
  { name: "TOML", value: "toml" },
  { name: "TypeScript", value: "typescript" },
  { name: "Vala", value: "vala" },
  { name: "VB.Net", value: "vbnet" },
  { name: "Verilog", value: "verilog" },
  { name: "VHDL", value: "vhdl" },
  { name: "Visual Basic", value: "visual-basic" },
  { name: "WebAssembly", value: "wasm" },
  { name: "XML", value: "xml" },
  { name: "YAML", value: "yaml" },
  { name: "Zig", value: "zig" },
];

export default languagesList;
